Module2
letucennik/gift-certificates pull request #1
Opened 2021-06-22 09:45 UTC by letucennik

2021-06-22 10:03 UTC, SenPavel requested changes

2021-06-22 10:03 UTC, SenPavel commented on repository/pom.xml
> +    </build>
Is the "war" plugin needed in the repository?

2021-06-22 10:03 UTC, SenPavel commented on repository/src/test/java/com/epam/esm/repository/impl/CertificateTagRepositoryImplTest.java
> +@Component
The Component annotation is not needed here

2021-06-22 10:03 UTC, SenPavel commented on repository/src/test/java/com/epam/esm/repository/impl/GiftCertificateRepositoryImplTest.java
> +@Component
the same

2021-06-22 10:03 UTC, SenPavel commented on repository/src/test/java/com/epam/esm/repository/impl/GiftCertificateRepositoryImplTest.java
> +@ComponentScan("com.epam.esm.entity.mapper")
If component scan is needed, move it to TestJdbcConfig

2021-06-22 10:03 UTC, SenPavel commented on repository/src/test/java/com/epam/esm/repository/impl/GiftCertificateRepositoryImplTest.java
> +        assertTrue(giftCertificate.isPresent() && giftCertificate.get().getId() == firstCertificate.getId());
Please divide this assert into two asserts, assertTrue for isPresent and assertEquals for giftCertificate.get().getId() == firstCertificate.getId()

2021-06-22 10:03 UTC, SenPavel commented on repository/src/test/java/com/epam/esm/repository/impl/GiftCertificateRepositoryImplTest.java
> +        assertTrue(certificate.isPresent() && certificate.get().getName().equals("certificate new name"));
the same

2021-06-22 10:03 UTC, SenPavel commented on repository/src/test/java/com/epam/esm/repository/impl/TagRepositoryImplTest.java
> +@Component
the same

2021-06-22 10:03 UTC, SenPavel commented on repository/src/test/java/com/epam/esm/repository/impl/TagRepositoryImplTest.java
> +        assertTrue(tag.isPresent() && tag.get().equals(firstTag));
the same for asserts

2021-06-22 10:03 UTC, SenPavel commented on service/pom.xml
> +    </build>
Is it needed in the service?

2021-06-22 10:03 UTC, SenPavel commented on web/pom.xml
> +                </plugin>
Are these plugins needed?

2021-06-22 20:28 UTC, maximelyashevich approved these changes
Reviewed from my side, good job.

Regards,
Maks

2021-06-22 20:28 UTC, maximelyashevich commented on repository/src/main/java/com/epam/esm/config/DataSourceConfig.java
> +    @Autowired
Please check if this annotation is really needed here.

2021-06-22 20:28 UTC, maximelyashevich commented on repository/src/main/java/com/epam/esm/repository/impl/CertificateTagRepositoryImpl.java
> +    }
**Just an idea:** it is also convenient to use `@RequiredArgsConstructor` instead.

2021-06-22 20:28 UTC, maximelyashevich commented on service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +        }
What's about ternary operator?

2021-06-23 14:02 UTC, letucennik commented on repository/pom.xml
> +    </build>
removed it

2021-06-23 14:02 UTC, letucennik commented on repository/src/test/java/com/epam/esm/repository/impl/CertificateTagRepositoryImplTest.java
> +@Component
done

2021-06-23 14:03 UTC, letucennik commented on repository/src/test/java/com/epam/esm/repository/impl/GiftCertificateRepositoryImplTest.java
> +@Component
done

2021-06-23 14:04 UTC, letucennik commented on repository/src/test/java/com/epam/esm/repository/impl/GiftCertificateRepositoryImplTest.java
> +@ComponentScan("com.epam.esm.entity.mapper")
done

2021-06-23 14:07 UTC, letucennik commented on repository/src/test/java/com/epam/esm/repository/impl/GiftCertificateRepositoryImplTest.java
> +        assertTrue(giftCertificate.isPresent() && giftCertificate.get().getId() == firstCertificate.getId());
done

2021-06-23 14:10 UTC, letucennik commented on repository/src/test/java/com/epam/esm/repository/impl/GiftCertificateRepositoryImplTest.java
> +        assertTrue(certificate.isPresent() && certificate.get().getName().equals("certificate new name"));
done

2021-06-23 14:10 UTC, letucennik commented on repository/src/test/java/com/epam/esm/repository/impl/TagRepositoryImplTest.java
> +@Component
done

2021-06-23 14:12 UTC, letucennik commented on repository/src/test/java/com/epam/esm/repository/impl/TagRepositoryImplTest.java
> +        assertTrue(tag.isPresent() && tag.get().equals(firstTag));
done

2021-06-23 14:15 UTC, letucennik commented on service/pom.xml
> +    </build>
no, removed it

2021-06-23 14:17 UTC, letucennik commented on web/pom.xml
> +                </plugin>
only war is needed, removed the rest

2021-06-23 14:25 UTC, letucennik commented on repository/src/main/java/com/epam/esm/config/DataSourceConfig.java
> +    @Autowired
Autowired annotation is not needed, removed it

2021-06-23 14:35 UTC, letucennik commented on service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +        }
good idea)

2021-06-23 14:40 UTC, letucennik commented on repository/src/main/java/com/epam/esm/repository/impl/CertificateTagRepositoryImpl.java
> +    }
done

2021-06-23 15:15 UTC, SenPavel approved these changes

2021-06-28 14:49 UTC, merged