Module3
letucennik/gift-certificates pull request #2
Opened 2021-07-13 15:47 UTC by letucennik

2021-07-13 15:59 UTC, SenPavel requested changes

2021-07-13 15:59 UTC, SenPavel commented on service/src/main/java/com/epam/esm/service/config/ServiceConfig.java
> +@org.springframework.context.annotation.Configuration
Please use import instead of fully qualified class name

2021-07-13 15:59 UTC, SenPavel commented on service/src/main/java/com/epam/esm/service/impl/OrderServiceImpl.java
> +        if(orderCertificates==null||orderCertificates.isEmpty()){
spaces

2021-07-13 15:59 UTC, SenPavel commented on repository/src/main/java/com/epam/esm/repository/impl/TagRepositoryImpl.java
> +                        " GROUP BY tag_id ORDER BY tag_count DESC LIMIT 1) AS b", Tag.class)
Please make this SQL script as class constant

2021-07-13 18:27 UTC, letucennik commented on service/src/main/java/com/epam/esm/service/config/ServiceConfig.java
> +@org.springframework.context.annotation.Configuration
done

2021-07-13 18:28 UTC, letucennik commented on service/src/main/java/com/epam/esm/service/impl/OrderServiceImpl.java
> +        if(orderCertificates==null||orderCertificates.isEmpty()){
done

2021-07-13 18:30 UTC, letucennik commented on repository/src/main/java/com/epam/esm/repository/impl/TagRepositoryImpl.java
> +                        " GROUP BY tag_id ORDER BY tag_count DESC LIMIT 1) AS b", Tag.class)
done

2021-07-13 19:08 UTC, SenPavel approved these changes

2021-07-15 10:42 UTC, NatalliaKhadunai reviewed
Left a couple of comments :) Just a note here: I'm not 100% sure that I'm right in all the cases, you know your code better than I do. So please feel free to argue with me and ask any questions you have.

2021-07-15 10:42 UTC, NatalliaKhadunai commented on web/src/main/resources/errorMessage_ru.properties
> +user.not.found=\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c\u0020\u043d\u0435\u0020\u043d\u0430\u0439\u0434\u0435\u043d
It would be better to store Russian messages as is and not using these encoded characters. 
As far as I remember it can be a bit challenging to implement this :)

2021-07-15 10:42 UTC, NatalliaKhadunai commented on web/src/main/java/com/epam/esm/controller/exception/RestExceptionHandler.java
>          return buildResponse(resolveResourceBundleMessage(e.getMessage(), locale), 40001);
It would be better to move these error codes (like here `40001`) to constants or at least add some meaningful comment to explain what they mean.
Now when I look at them I have absolutely no idea what do they mean.

2021-07-15 10:42 UTC, NatalliaKhadunai commented on web/src/main/java/com/epam/esm/controller/GiftCertificateController.java
> +        return certificates.stream().peek(certificateDtoLinkAdder::addLinks).collect(Collectors.toList());
In the documentation to the `peek()` method it follows that 1) it should be used primarily for debugging purposes, 2) some internal stream optimizations may not be used if `peek()` in the method chain. It'd be better to replace it with some other method.

2021-07-15 10:42 UTC, NatalliaKhadunai commented on web/src/main/java/com/epam/esm/controller/OrderController.java
> +        dto.setUser(userService.read(userId));
Looks like this piece of code (setting user to dto) belongs to the service layer, not to the controller layer.

2021-07-15 10:42 UTC, NatalliaKhadunai commented on service/src/main/java/com/epam/esm/service/dto/mapper/impl/GiftCertificateMapper.java
> +        TagMapper mapper = new TagMapper(new ModelMapper());
It's not quite clear to me why do we create instances of these classes. Why can't we use injected instances?

2021-07-15 10:42 UTC, NatalliaKhadunai commented on service/src/main/java/com/epam/esm/service/dto/mapper/impl/OrderMapper.java
> +        order.getCertificates().clear();
Why do we clear a collection here? Is it safe from DB standpoint?

2021-07-15 10:42 UTC, NatalliaKhadunai commented on service/src/main/java/com/epam/esm/service/impl/OrderServiceImpl.java
> +        if (orderDto.getUser().getId() < 0) {
The order of validation operations seems a bit confusing to me. At first, we're run a search in the DB looking for a user using his id and after this validation passes we're checking whether id is > 0

2021-07-15 10:42 UTC, NatalliaKhadunai commented on service/src/main/java/com/epam/esm/service/impl/OrderServiceImpl.java
> +        if (!userRepository.read(userId).isPresent()) {
Maybe it would be better to use `orElseThrow` here?

2021-07-15 10:42 UTC, NatalliaKhadunai commented on service/src/main/java/com/epam/esm/service/impl/OrderServiceImpl.java
> +        if (userOrders == null || userOrders.isEmpty() || !userOrders.contains(foundOrder)) {
It looks like this approach is going to be quite resource-consuming. Getting all user orders just to find whether an order belongs to a user or not.... Probably we can try to reimplement this logic and do it using some DB operations?

2021-07-15 10:42 UTC, NatalliaKhadunai commented on service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +            throw new InvalidParameterException("certificate.invalid");
I think validation exceptions should be more specific, API client should be able to understand which part of the request is not valid.

2021-07-15 10:42 UTC, NatalliaKhadunai commented on repository/src/main/resources/db.properties
>  db.password=Peter979
We should not commit passwords

2021-07-15 10:42 UTC, NatalliaKhadunai commented on repository/src/main/java/com/epam/esm/repository/config/DataSourceConfig.java
> +package com.epam.esm.repository.config;
Regarding this class `DataSourceConfig` I'm a bit confused regarding why do we have it at all. I thought that since we're using Spring Boot we just need to set DB properties in Spring Boot property files and DB classes will be configured for us. 
I may be wrong, probably the approach that I've described work with Spring Data only, not sure

2021-07-15 10:42 UTC, NatalliaKhadunai commented on repository/src/main/java/com/epam/esm/repository/entity/CertificateTag.java
> +public class CertificateTag {
Can we avoid using this class and use `ManyToMany` mapping in `GiftCertificate` and `Tag` classes?

2021-07-15 10:42 UTC, NatalliaKhadunai commented on repository/src/main/java/com/epam/esm/repository/impl/OrderRepositoryImpl.java
> +        Join<User, Order> userJoin = root.join("user");
As far as I can see in `Order` class mapping for `User` is eager. Not quite clear to me why do we need this join...

2021-07-15 10:42 UTC, NatalliaKhadunai commented on repository/src/main/java/com/epam/esm/repository/entity/GiftCertificate.java
> +    private int duration;
Storing `duration` as an `int` in Java code is very confusing. Other developers will never know what is the unit of measurement here. You can consider using class `Duration`.

2021-07-15 11:53 UTC, letucennik commented on web/src/main/java/com/epam/esm/controller/exception/RestExceptionHandler.java
>          return buildResponse(resolveResourceBundleMessage(e.getMessage(), locale), 40001);
I agree it may be confusing to understand their meaning, so I introduced constants for codes

2021-07-15 12:05 UTC, letucennik commented on web/src/main/java/com/epam/esm/controller/GiftCertificateController.java
> +        return certificates.stream().peek(certificateDtoLinkAdder::addLinks).collect(Collectors.toList());
I wanted to see this method work) replaced it with forEach

2021-07-15 12:08 UTC, letucennik commented on web/src/main/resources/errorMessage_ru.properties
> +user.not.found=\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c\u0020\u043d\u0435\u0020\u043d\u0430\u0439\u0434\u0435\u043d
it is challenging, I could not find any proper tutorial for it

2021-07-15 12:18 UTC, letucennik commented on web/src/main/java/com/epam/esm/controller/OrderController.java
> +        dto.setUser(userService.read(userId));
I believe it makes more sense to do it in controller layer,since OrderDto has an instance of UserDto in it, not just User. I'm not sure it is good practice to use other services within OrderService

2021-07-15 12:23 UTC, letucennik commented on service/src/main/java/com/epam/esm/service/dto/mapper/impl/GiftCertificateMapper.java
> +        TagMapper mapper = new TagMapper(new ModelMapper());
I forgot to change it during refactoring) fixed this mistake

2021-07-15 17:04 UTC, letucennik commented on service/src/main/java/com/epam/esm/service/dto/mapper/impl/OrderMapper.java
> +        order.getCertificates().clear();
it's a silly mistake, fixed it

2021-07-15 17:17 UTC, letucennik commented on service/src/main/java/com/epam/esm/service/impl/OrderServiceImpl.java
> +        if (orderDto.getUser().getId() < 0) {
fixed it

2021-07-15 17:20 UTC, letucennik commented on service/src/main/java/com/epam/esm/service/impl/OrderServiceImpl.java
> +        if (!userRepository.read(userId).isPresent()) {
changed it

2021-07-15 17:30 UTC, letucennik commented on repository/src/main/java/com/epam/esm/repository/entity/CertificateTag.java
> +public class CertificateTag {
There may be additional fields in CertificateTag entity in future. Besides, I wanted to try several approaches for implementing many-to-many relationship. I have ManyToMany in order-certificate relationship

2021-07-15 18:15 UTC, letucennik commented on service/src/main/java/com/epam/esm/service/impl/OrderServiceImpl.java
> +        if (userOrders == null || userOrders.isEmpty() || !userOrders.contains(foundOrder)) {
I agree that it is resource-consuming, reimplemented this method, added new functionality to OrderRepository

2021-07-16 07:11 UTC, NatalliaKhadunai commented on service/src/main/java/com/epam/esm/service/impl/OrderServiceImpl.java
> +        if (orderDto.getUser().getId() < 0) {
@letucennik BTW, why don't we use some validator here?

2021-07-16 07:14 UTC, NatalliaKhadunai commented on service/src/main/java/com/epam/esm/service/impl/OrderServiceImpl.java
> +        if (!userRepository.read(userId).isPresent()) {
@letucennik thanks! As far as I can see the same construction (I mean "if optional is present then throw an exception") is still used in some other places. You may want to implement the same fix there when you have some time

2021-07-16 07:16 UTC, NatalliaKhadunai commented on service/src/main/java/com/epam/esm/service/impl/OrderServiceImpl.java
> +        if (userOrders == null || userOrders.isEmpty() || !userOrders.contains(foundOrder)) {
@letucennik now it looks better, thanks! 
Another question I have about this method is whether we need this piece of code:
`userRepository.read(userId).orElseThrow(() -> new NoSuchEntityException(USER_NOT_FOUND));`

2021-07-16 07:21 UTC, NatalliaKhadunai commented on repository/src/main/java/com/epam/esm/repository/entity/CertificateTag.java
> +public class CertificateTag {
@letucennik got it, but what field do you think may be added here? :) I think in a many-to-many relationship we never have any other fields in linking tables except entities ids.
BTW usually when we're saying smth like "I think it can be useful in the future" it rarely becomes useful :) You can read about the YAGNI principle to understand why we shouldn't implement smth "for the future".

P.s. You can leave this code as-is for now, I don't mind a lot as you're saying that you were just trying and trying smth new is a good thing :)

2021-07-17 10:13 UTC, letucennik commented on service/src/main/java/com/epam/esm/service/impl/OrderServiceImpl.java
> +        if (orderDto.getUser().getId() < 0) {
that's a good idea) I put validation in a separate method, which calls UserValidator methods

2021-07-17 10:15 UTC, letucennik commented on service/src/main/java/com/epam/esm/service/impl/OrderServiceImpl.java
> +        if (userOrders == null || userOrders.isEmpty() || !userOrders.contains(foundOrder)) {
Yes, it is needed when a client tries to find certificates of a user, that doesn't exist

2021-07-17 10:28 UTC, letucennik commented on service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +            throw new InvalidParameterException("certificate.invalid");
I agree, specified it

2021-07-17 11:44 UTC, closed without merging